import type { Metadata } from "next";
import "./globals.css";
import React from "react";
import { Footer } from "../components";

export const metadata: Metadata = {
  title: "RCL Rentals Informational Website",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <main className="flex-grow">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
