export const productList = [
  {
    title: "MacBook Air 13.6",
    description: "Apple M2 chip, 8GB Memory, 256GB SSD,  8-core GPU, Liquid",
    id:"1",
    link: "/1.png",
  },
  {
    title: "MacBook Air 13.6",
    description: "Apple M2 chip, 8GB Memory, 256GB SSD,  8-core GPU, Liquid",
    id:"2",
    link: "/2.png",
  },
  {
    title: "MacBook Air 13.6",
    description: "Apple M2 chip, 8GB Memory, 256GB SSD,  8-core GPU, Liquid",
    id:"3",
    link: "/3.png",
  },
  {
    title: "MacBook Air 13.6",
    description: "Apple M2 chip, 8GB Memory, 256GB SSD,  8-core GPU, Liquid",
    id:"4",
    link: "/4.png",
  },
  {
    title: "MacBook Air 13.6",
    description: "Apple M2 chip, 8GB Memory, 256GB SSD,  8-core GPU, Liquid",
    id:"5",
    link: "/5.png",
  },
  {
    title: "MacBook Air 13.6",
    description: "Apple M2 chip, 8GB Memory, 256GB SSD,  8-core GPU, Liquid",
    id:"6",
    link: "/6.png",
  },
  {
    title: "MacBook Air 13.6",
    description: "Apple M2 chip, 8GB Memory, 256GB SSD,  8-core GPU, Liquid",
    id:"7",
    link: "/7.png",
  },
  {
    title: "MacBook Air 13.6",
    description: "Apple M2 chip, 8GB Memory, 256GB SSD,  8-core GPU, Liquid",
    id:"8",
    link: "/8.png",
  },
  {
    title: "MacBook Air 13.6",
    description: "Apple M2 chip, 8GB Memory, 256GB SSD,  8-core GPU, Liquid",
    id:"9",
    link: "/9.png",
  },
  {
    title: "MacBook Air 13.6",
    description: "Apple M2 chip, 8GB Memory, 256GB SSD,  8-core GPU, Liquid",
    id:"10",
    link: "/10.png",
  },
  {
    title: "MacBook Air 13.6",
    description: "Apple M2 chip, 8GB Memory, 256GB SSD,  8-core GPU, Liquid",
    id:"13",
    link: "/13.png",
  },
  {
    title: "MacBook Air 13.6",
    description: "Apple M2 chip, 8GB Memory, 256GB SSD,  8-core GPU, Liquid",
    id:"14",
    link: "/14.png",
  },
  {
    title: "MacBook Air 13.6",
    description: "Apple M2 chip, 8GB Memory, 256GB SSD,  8-core GPU, Liquid",
    id:"11",
    link: "/11.png",
  },
  {
    title: "MacBook Air 13.6",
    description: "Apple M2 chip, 8GB Memory, 256GB SSD,  8-core GPU, Liquid",
    id:"12",
    link: "/12.png",
  },
  {
    title: "MacBook Air 13.6",
    description: "Apple M2 chip, 8GB Memory, 256GB SSD,  8-core GPU, Liquid",
    id:"15",
    link: "/15.png",
  },
  {
    title: "MacBook Air 13.6",
    description: "Apple M2 chip, 8GB Memory, 256GB SSD,  8-core GPU, Liquid",
    id:"16",
    link: "/16.png",
  },
  {
    title: "MacBook Air 13.6",
    description: "Apple M2 chip, 8GB Memory, 256GB SSD,  8-core GPU, Liquid",
    id:"17",
    link: "/17.png",
  },
  {
    title: "MacBook Air 13.6",
    description: "Apple M2 chip, 8GB Memory, 256GB SSD,  8-core GPU, Liquid",
    id:"18",
    link: "/18.png",
  },
  {
    title: "MacBook Air 13.6",
    description: "Apple M2 chip, 8GB Memory, 256GB SSD,  8-core GPU, Liquid",
    id:"19",
    link: "/19.png",
  },
  {
    title: "MacBook Air 13.6",
    description: "Apple M2 chip, 8GB Memory, 256GB SSD,  8-core GPU, Liquid",
    id:"20",
    link: "/20.png",
  },
  {
    title: "MacBook Air 13.6",
    description: "Apple M2 chip, 8GB Memory, 256GB SSD,  8-core GPU, Liquid",
    id:"21",
    link: "/21.png",
  },
  {
    title: "MacBook Air 13.6",
    description: "Apple M2 chip, 8GB Memory, 256GB SSD,  8-core GPU, Liquid",
    id:"22",
    link: "/22.png",
  },
  {
    title: "MacBook Air 13.6",
    description: "Apple M2 chip, 8GB Memory, 256GB SSD,  8-core GPU, Liquid",
    id:"23",
    link: "/23.png",
  },
  {
    title: "MacBook Air 13.6",
    description: "Apple M2 chip, 8GB Memory, 256GB SSD,  8-core GPU, Liquid",
    id:"24",
    link: "/24.png",
  },
  {
    title: "MacBook Air 13.6",
    description: "Apple M2 chip, 8GB Memory, 256GB SSD,  8-core GPU, Liquid",
    id:"25",
    link: "/25.png",
  },
];
